name: abcd_analysis
channels:
  - conda-forge
  - ejolly
dependencies:
  - pymer4
  - polars>=1.31.0,<2
  - statsmodels>=0.14.4,<0.15
  - pandas
  - matplotlib
  - scikit-learn
  - ipykernel
  - plotly
  - openpyxl
  - numpy
